# Generated by Django 3.2.7 on 2021-10-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='type_of_dish',
            field=models.CharField(choices=[('STARTER', 'Starter'), ('MAIN', 'Main dish'), ('DESSERT', 'Dessert')], default='MAIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description_text',
            field=models.CharField(max_length=1000),
        ),
    ]
