# Generated by Django 3.2.7 on 2021-10-26 08:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20211024_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='dish',
            name='type_of_dish',
            field=models.CharField(choices=[('STARTER', 'Starter'), ('MAIN', 'Main dish'), ('DESSERT', 'Dessert'), ('DRINK', 'Drink')], default='MAIN', max_length=50),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.dish')),
            ],
        ),
    ]
