# Generated by Django 3.2.7 on 2021-10-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20211026_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_notes',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
